# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTAoNT_I2TacPKPW6H-D7gCKS2sV5oph
"""

import streamlit as st
import av
import cv2
import os
import zipfile
import tempfile
from datetime import datetime
from collections import defaultdict

import numpy as np
import pandas as pd

from ultralytics import YOLO
from streamlit_webrtc import webrtc_streamer, VideoProcessorBase

from streamlit_geolocation import streamlit_geolocation
from streamlit_folium import st_folium
import folium

# ======================================================
# CONFIGURACIÓN
# ======================================================

st.set_page_config(
    page_title="Detector IA de Residuos",
    page_icon="🗑️",
    layout="wide"
)

st.title("🗑️ Detector Inteligente de Residuos")

# ======================================================
# CARGAR MODELO
# ======================================================

@st.cache_resource
def cargar_modelo():
    return YOLO("best.pt")

modelo = cargar_modelo()

# ======================================================
# SESIÓN
# ======================================================

if "conteo" not in st.session_state:
    st.session_state.conteo = defaultdict(int)

if "ids_contados" not in st.session_state:
    st.session_state.ids_contados = set()

if "registro" not in st.session_state:
    st.session_state.registro = []

if "capturas" not in st.session_state:
    st.session_state.capturas = []

if "inspeccion_iniciada" not in st.session_state:
    st.session_state.inspeccion_iniciada = False

if "hora_inicio" not in st.session_state:
    st.session_state.hora_inicio = None

# ======================================================
# CARPETA DE CAPTURAS
# ======================================================

CAPTURAS_DIR = "capturas"

os.makedirs(CAPTURAS_DIR, exist_ok=True)

# ======================================================
# SIDEBAR
# ======================================================

st.sidebar.title("⚙️ Configuración")

confianza = st.sidebar.slider(
    "Confianza",
    0.10,
    1.00,
    0.40,
    0.05
)

camara = st.sidebar.selectbox(
    "Cámara",
    [
        "Trasera",
        "Delantera"
    ]
)

if camara == "Trasera":

    video_constraints = {
        "video": {
            "facingMode": {
                "ideal": "environment"
            }
        },
        "audio": False
    }

else:

    video_constraints = {
        "video": {
            "facingMode": "user"
        },
        "audio": False
    }

# ======================================================
# BOTONES
# ======================================================

col1, col2 = st.columns(2)

with col1:

    if st.button("▶️ Iniciar inspección", use_container_width=True):

        st.session_state.inspeccion_iniciada = True
        st.session_state.hora_inicio = datetime.now()

        st.success("Inspección iniciada.")

with col2:

    if st.button("⏹ Finalizar inspección", use_container_width=True):

        st.session_state.inspeccion_iniciada = False

        st.success("Inspección finalizada.")

# ======================================================
# GPS
# ======================================================

ubicacion = streamlit_geolocation()

latitud = None
longitud = None

if ubicacion is not None:

    latitud = ubicacion.get("latitude")
    longitud = ubicacion.get("longitude")

    if latitud is not None:

        st.sidebar.success("📍 GPS conectado")

        st.sidebar.write(
            f"Lat: {latitud:.6f}"
        )

        st.sidebar.write(
            f"Lon: {longitud:.6f}"
        )

else:

    st.sidebar.warning(
        "Esperando permiso del GPS..."
    )

# ======================================================
# FUNCIONES
# ======================================================

def guardar_csv():

    df = pd.DataFrame(
        st.session_state.registro
    )

    df.to_csv(
        "detecciones.csv",
        index=False
    )

    return df


def guardar_captura(imagen):

    nombre = datetime.now().strftime(
        "%Y%m%d_%H%M%S_%f"
    )

    ruta = os.path.join(
        CAPTURAS_DIR,
        f"{nombre}.jpg"
    )

    cv2.imwrite(ruta, imagen)

    st.session_state.capturas.append(
        ruta
    )

    return ruta


def crear_zip():

    zip_path = os.path.join(
        tempfile.gettempdir(),
        "capturas.zip"
    )

    with zipfile.ZipFile(
        zip_path,
        "w"
    ) as z:

        for archivo in st.session_state.capturas:

            if os.path.exists(archivo):

                z.write(
                    archivo,
                    os.path.basename(archivo)
                )

    return zip_path

# ======================================================
# DETECTOR (YOLO + BYTETRACK)
# ======================================================

class Detector(VideoProcessorBase):

    def recv(self, frame):

        global latitud, longitud

        imagen = frame.to_ndarray(format="bgr24")

        # Si la inspección no ha iniciado, solo mostrar la cámara
        if not st.session_state.inspeccion_iniciada:
            return av.VideoFrame.from_ndarray(
                imagen,
                format="bgr24"
            )

        resultados = modelo.track(
            imagen,
            persist=True,
            tracker="bytetrack.yaml",
            conf=confianza,
            verbose=False
        )

        resultado = resultados[0]

        # ==================================================
        # CONTAR SOLO IDS NUEVOS
        # ==================================================

        if (
            resultado.boxes is not None
            and resultado.boxes.id is not None
        ):

            ids = resultado.boxes.id.cpu().numpy().astype(int)
            clases = resultado.boxes.cls.cpu().numpy().astype(int)
            confs = resultado.boxes.conf.cpu().numpy()

            for obj_id, clase, conf in zip(ids, clases, confs):

                # Si ya fue contado anteriormente
                if obj_id in st.session_state.ids_contados:
                    continue

                st.session_state.ids_contados.add(obj_id)

                nombre = modelo.names[clase]

                st.session_state.conteo[nombre] += 1

                # Guardar captura
                ruta_imagen = guardar_captura(imagen)

                # Registrar información
                registro = {

                    "fecha": datetime.now().strftime("%Y-%m-%d"),

                    "hora": datetime.now().strftime("%H:%M:%S"),

                    "id_objeto": int(obj_id),

                    "clase": nombre,

                    "confianza": round(float(conf), 3),

                    "latitud": latitud,

                    "longitud": longitud,

                    "imagen": ruta_imagen

                }

                st.session_state.registro.append(
                    registro
                )

        # ==================================================
        # DIBUJAR DETECCIONES
        # ==================================================

        salida = resultado.plot()

        return av.VideoFrame.from_ndarray(
            salida,
            format="bgr24"
        )


# ======================================================
# GUARDAR CSV EN CADA DETECCIÓN
# ======================================================

if len(st.session_state.registro) > 0:

    guardar_csv()

# ======================================================
# WEBCAM STREAMLIT WEBRTC
# ======================================================

st.markdown("## 📷 Cámara en tiempo real")

webrtc_streamer(
    key="detector-residuos",
    video_processor_factory=Detector,
    media_stream_constraints=video_constraints,
    async_processing=True
)

# ======================================================
# CONTEO EN TIEMPO REAL
# ======================================================

st.sidebar.markdown("## 🗑️ Conteo de residuos")

if len(st.session_state.conteo) > 0:

    for clase, cantidad in st.session_state.conteo.items():

        st.sidebar.write(f"**{clase}**: {cantidad}")

else:

    st.sidebar.info("Sin detecciones aún")

# ======================================================
# MAPA EN TIEMPO REAL
# ======================================================

st.markdown("## 🗺️ Mapa de detecciones")

df_map = pd.DataFrame(st.session_state.registro)

if len(df_map) > 0 and "latitud" in df_map.columns:

    df_map_clean = df_map.dropna(
        subset=["latitud", "longitud"]
    )

    if len(df_map_clean) > 0:

        df_map_clean = df_map_clean.rename(
            columns={
                "latitud": "lat",
                "longitud": "lon"
            }
        )

        st.map(df_map_clean[["lat", "lon"]])

    else:

        st.warning("Aún no hay datos GPS válidos")

else:

    st.info("Mapa se activará cuando haya detecciones con GPS")

# ======================================================
# RESUMEN RÁPIDO
# ======================================================

st.markdown("## 📊 Estado de la inspección")

col1, col2, col3 = st.columns(3)

with col1:

    st.metric(
        "Objetos detectados",
        len(st.session_state.registro)
    )

with col2:

    st.metric(
        "Tipos de residuos",
        len(st.session_state.conteo)
    )

with col3:

    if st.session_state.inspeccion_iniciada:

        st.success("🟢 Activa")

    else:

        st.error("🔴 Inactiva")

# ======================================================
# RESUMEN FINAL
# ======================================================

st.markdown("## 📊 Resumen de inspección")

if len(st.session_state.registro) > 0:

    df_final = pd.DataFrame(st.session_state.registro)

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(
            "Total detecciones",
            len(df_final)
        )

    with col2:
        st.metric(
            "Tipos de residuos",
            len(st.session_state.conteo)
        )

    with col3:
        if st.session_state.hora_inicio:

            duracion = datetime.now() - st.session_state.hora_inicio

            st.metric(
                "Duración",
                str(duracion).split(".")[0]
            )
        else:
            st.metric("Duración", "N/A")

    st.markdown("### 🗑️ Conteo por clase")

    for k, v in st.session_state.conteo.items():
        st.write(f"- **{k}**: {v}")

else:
    st.info("Aún no hay datos de inspección")

# ======================================================
# DESCARGAS
# ======================================================

st.markdown("## 📥 Exportar datos")

col1, col2 = st.columns(2)

with col1:

    if len(st.session_state.registro) > 0:

        csv_data = pd.DataFrame(
            st.session_state.registro
        ).to_csv(index=False).encode("utf-8")

        st.download_button(
            "📄 Descargar CSV",
            data=csv_data,
            file_name="detecciones.csv",
            mime="text/csv"
        )

with col2:

    if len(st.session_state.capturas) > 0:

        zip_path = crear_zip()

        with open(zip_path, "rb") as f:

            st.download_button(
                "📦 Descargar capturas",
                data=f,
                file_name="capturas.zip",
                mime="application/zip"
            )

# ======================================================
# RESET DE SESIÓN
# ======================================================

st.markdown("## 🔄 Nueva inspección")

if st.button("Resetear todo"):

    st.session_state.conteo = defaultdict(int)
    st.session_state.ids_contados = set()
    st.session_state.registro = []
    st.session_state.capturas = []
    st.session_state.inspeccion_iniciada = False
    st.session_state.hora_inicio = None

    st.success("Sesión reiniciada correctamente")